### ISSUE TITLE
Add Terry and Kodi as co-authors to this dataset since they do scanning

### ISSUE THREAD

**Issue by yarikoptic** [dbic/QA#1]
@kodiweera any objections?

**Comment by yarikoptic** [comment]
no objections were voiced and moreover we already had BIDS dataset_description.json with both of those folks.

I have created CITATION.cff and a .1 release for that purpose but release on zenodo ran into an issue since CITATION.cff expects SPDX id for a license - we used `PDDL`...  but that one is not standard either (so my support report to zenodo was a bit off ;)) -- trying PDDL-1.0 now!

**Comment by yarikoptic** [comment]
all good now: https://zenodo.org/record/8253053

**Comment by kodiweera** [comment]
We'll thank you with plenty of qa data!
